args <- commandArgs(trailingOnly = TRUE)

# usage: Step5a-3.GettingBranchLabelsForSwamp.R <dir that contains rst file>
# ## try http:// if https:// URLs are not supported
# source("http://bioconductor.org/biocLite.R")
# biocLite("treeio")
require(treeio)
require(ape)
require(Biostrings)
require(geiger)
#source("https://bioconductor.org/biocLite.R")
#biocLite("Biostrings")
# read in your rst file generated by running codeml model 0 using treeio
brst <- read.paml_rst(paste(as.character(args[1]),"/rst",sep=""))
# turn it into a tree 
tree <- get.tree(brst)
## use which.edge somehow
tipIDs <- as.data.frame(tree$tip.label)
tipIDs$tipNum <- rownames(tipIDs) # each tip gets a number (alphabetical bc fasta was sorted)
# this applies the 'tip' function to each node label
# get node IDs:
nodeIDs <- data.frame(tree$node.label,stringsAsFactors=F)
# from geiger, tips: tips(phy,node)
nodeIDs$tips <- sapply(as.integer(nodeIDs$tree.node.label),tips,phy=tree)
colnames(nodeIDs) <- c("num","tips")
colnames(tipIDs) <- c("tips","num")
tipIDs$tips <- as.list(as.character(tipIDs$tips)) # have to make labels a list type item for consistency
nodesAndTips <- rbind(tipIDs,nodeIDs)


tree$edge # gives you first part. Don't actually need intersection. The second set of edges gives you the information
edges <- data.frame(tree$edge)
colnames(edges) <- c("edge1","edge2")
head(edges)
# merge the nodesAndTips and edges by the edge2 number:
merged <- merge(edges,nodesAndTips,by.x="edge2",by.y="num")
# now just want to write this out in format edge2..edge1 <tab> tips with commas.
merged$test <- merged$tips
write.table(paste(merged$edge1,"..",merged$edge2," ",mapply(toString,merged$tips),sep=""),paste(args[1],"/branchLabels.specific.txt",sep=""),quote=F,row.names=F,col.names = F)
